version: "3.3"

services:
  nginx:
    container_name: nginx
    build: internal/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - core:/www

  core:
    container_name: core
    build: .
    command: bash bin/entrypoint.sh
    volumes:
      - core:/www
    depends_on:
      - nginx

volumes:
  core:
